name: 'Check Paclet'
description: 'Check a paclet using its definition notebook file'
branding:
  icon: 'check-circle'  
  color: 'orange'
inputs:
  target:  # id of input
    description: 'The target'
    required: false
    default: 'Submit'
  definition_notebook:
    description: 'Path to the definition notebook'
    required: false
    default: './ResourceDefinition.nb'
  debug:
    description: 'Whether to enable additional debug output'
    required: false
    default: 'false'
  paclet_cicd_version:
    description: 'Version of PacletCICD to use'
    required: false
    default: 'latest'
  resource_system_base:
    description: 'Specifies the location of the resource system'
    required: false
    default: 'https://www.wolframcloud.com/obj/resourcesystem/api/1.0'
runs:
  using: 'docker'
  image: 'Dockerfile'
